### ISSUE TITLE
[버그] 삭제된 서버를 리스트에서 삭제할 수 없음.

### ISSUE THREAD

**Issue by PencilQA** [koreanbots/core#481]
## 재현방법

> 서버를 서버 리스트에 추가한다.
> 해당 서버를 삭제한다.
> 해당 서버를 서버 리스트에서 삭제한다.

## 예상되는 정상적인 동작

> 서버 리스트에서 서버 리스트가 삭제되어야 함.

## 발생한 문제

> 서버 정보를 불러올 수 없다는 오류가 발생함.
![Screenshot_20211218-193429_Samsung Internet](https://user-images.githubusercontent.com/92716173/146638050-0f77b5dc-4b66-4e96-8418-1e95fa84b2cf.jpg)

## 빌드 버전

> 클라이언트의 빌드 버전을 알려주세요!

빌드정보
Tag: master
Version: v2.1.1

## 사양

> Android 11, Samsung Internet

## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
서버에서 봇이 추방되어 정보를 패치 할 수 없어 소유자 여부를 확인할 수 없어 발생하는 문제 같습니다. 봇을 서버에 초대한 상태로 삭제 해주세요.

**Comment by MracM0** [comment]
> 서버에서 봇이 추방되어 정보를 패치 할 수 없어 소유자 여부를 확인할 수 없어 발생하는 문제 같습니다. 봇을 서버에 초대한 상태로 삭제 해주세요.

서버를 삭제했는데 어떻게 봇을 초대하죠..

**Comment by wonderlandpark** [comment]
앗 공식 디스코드의 IU봇의 DM을 통해 문의해주시면 처리 해드리겠습니다.

https://koreanbots.dev/discord

**Comment by designed-re** [comment]
Completed.
