### ISSUE TITLE
Error: Could not find a production build in the '/home/runner/core/ | (sleep 2; wget http:/localhost:3000/api/v2/management/load -O /dev/null)/.next'  directory

### ISSUE THREAD

**Issue by Aceeeeeeeeeee** [koreanbots/core#487]
`Error: Could not find a production build in the '/home/runner/core/ | (sleep 2; wget http:/localhost:3000/api/v2/management/load -O /dev/null)/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id`

**Comment by wonderlandpark** [comment]
Under license, we disclaim warranty for self-hosted cases. Only bugs corresponding to the actual service can be submitted in the issue. Have a nice day :)
