### ISSUE TITLE
[버그] 봇 초대링크 생성기 버그

### ISSUE THREAD

**Issue by hminkoo10** [koreanbots/core#488]
## 재현방법

> 어떻게하면 발생시킬 수 있나요?
https://koreanbots.dev/calculator
봇 초대링크 생성기에서 채팅채널 권한에 빗금 명령어 사용을 체크하면 버그가 발생됩니다

## 예상되는 정상적인 동작

> 정상이라면 어떻게 되야하나요?
정상적으로 초대가 되야합니다

## 발생한 문제

> 어떤 문제가 발생하나요?
permission코드가 2147483648로 되야하나 앞에 -가 붙어 알 수 없는 permission코드라고 나와서 초대가 불가능합니다

## 빌드 버전

> 클라이언트의 빌드 버전을 알려주세요!
master
v2.1.1

## 사양

> OS 정보와 브라우저의 버전을 알려주세요!
Windows 11 Pro
네이버 웨일 / 버전 3.13.131.36(공식 빌드) (64비트)
## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by SaidBySolo** [comment]
해당 이슈는 프론트 공고 모집이 완료되면 fix될 예정같아요.
