### ISSUE TITLE
[버그] 서버 위젯 서버 이름 길이가 넓을시 Korealist 로고 가리는 이슈

### ISSUE THREAD

**Issue by filename24** [koreanbots/core#533]
## 재현방법

> 어떻게하면 발생시킬 수 있나요?
1. 서버 이름을 길게 작성한다

![image](https://user-images.githubusercontent.com/63600304/214545112-ed94005f-6785-4300-a069-805927dff01d.png)

## 발생 위치
- 발생 위치 `og.koreanbots.dev`
- [자세한 위치](https://og.koreanbots.dev/Infinite%20Studio%20%EA%B3%B5%EC%8B%9D%20%EC%84%9C%ED%8F%AC%ED%8A%B8%EC%84%BC%ED%84%B0.png?image=https%3A%2F%2Fkoreanbots.dev%2Fapi%2Fimage%2Fdiscord%2Ficons%2F689375730483855389.webp%3Fsize%3D256&bio=%EB%94%94%EC%8A%A4%EC%BD%94%EB%93%9C+%EB%B4%87+%EA%B0%9C%EB%B0%9C%ED%8C%80+InfiniteTeam.+%ED%95%9C%EA%B5%AD+%EC%B5%9C%EC%B4%88+%EB%8C%80%EC%8B%9C%EB%B3%B4%EB%93%9C+%EA%B4%80%EB%A6%AC%EB%B4%87+Aztra%EB%A5%BC+%EA%B0%9C%EB%B0%9C%ED%95%A9%EB%8B%88%EB%8B%A4.&type=server&tags=%EB%B4%87&tags=%EC%BB%A4%EB%AE%A4%EB%8B%88%ED%8B%B0&tags=IT+%26+%EA%B3%BC%ED%95%99&stats=1&stats=510)
## 예상되는 정상적인 동작

> 정상이라면 어떻게 되야하나요?

1. 특정 길이를 넘을시 폰트가 작아져야함

## 발생한 문제

> 어떤 문제가 발생하나요?

- Koreanlist 로고 가려진다
- 디자인적으로 보기 안좋다

## 빌드 버전

> 클라이언트의 빌드 버전을 알려주세요!

Tag: master
Version: v2.1.1
Hash: null

## 사양

> OS 정보와 브라우저의 버전을 알려주세요!
- 네이버 웨일 3.18.154.13
- 디스코드 Canary 169696 (8b3d1ab) [위젯 표시]
- Windows 11 Pro 22H2

## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by skinmaker1345** [comment]
해결되었습니다.
