### ISSUE TITLE
[버그] [CR] 깃허브 계정 연동 취소 클릭시 502 응답

### ISSUE THREAD

**Issue by kyutorials** [koreanbots/core#628]
## 재현방법

23.10.01 preRelease 확인됨

> 어떻게하면 발생시킬 수 있나요?

0. 사전 조건 : 한국 디스코드 리스트 (이하 한디리) 에 깃허브 계정 연동 (프로필 노출)
1. 디스코드 로그인
2. 우측 상단 "관리 패널" 클릭
3. "깃허브 계정 연동 취소" 클릭

즉, 아래 코드의 API 가 호출될때 입니다.
https://github.com/koreanbots/core/blob/606f3cbc82919756fe7ac8691f1449857be4e1d5/pages/panel.tsx#L32-L40

## 예상되는 정상적인 동작

> 정상이라면 어떻게 되야하나요?

깃허브 계정 연동이 해제되고 프로필에 노출되지 않음

## 발생한 문제

> 어떤 문제가 발생하나요?

서버 요청 후 API가 장시간 Pending 상태에 있다가 502 상태를 반환

![image](https://github.com/koreanbots/core/assets/140045170/5168b0e0-10ff-49f8-bf3b-1b7880359363)

HTTP 502 추측 원인
- 추측1. 버튼 클릭시 호출되는 API [DELETE] /api/auth/github 에서 처리되지 않은 예외로 인해 종료되고 일정 시간 후 재실행
- 추측2. 해당 API 주소에 대해 CloudFlare가 한디리 Endpoint 와 연결에 실패
- 추측3. 해당 API 주소에 대해 CloudFlare가 사용자의 IP 주소를 차단해서 발생
  - 모바일 데이터에서도 동일하게 발생하므로 특정 IP 문제는 아님으로 보입니다.

## 빌드 버전

> 클라이언트의 빌드 버전을 알려주세요!
Tag: v2.6.6
Version: v2.6.6
Hash: 7c8b77fe99eaae7ef8a8b0a8f85646ec017ef550

## 사양

> OS 정보와 브라우저의 버전을 알려주세요!

OS : Windows 10 Version 22H2 (Build 19045.3448)

브라우저 : 크롬 - 117.0.5938.132 (공식 빌드) (64비트) (cohort: M117_Stable)

브라우저 Javascript : V8 11.7.439.19

브라우저 요청 UA : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by eunwoo1104** [comment]
v2.6.7-pre 버전에서 문제가 해결되었습니다.

다만, 악용 우려를 방지하기 위해 앞으로 실제 서비스에 심각한 영향을 끼칠 수 있는 문제에 대해서는 [버그 바운티 프로그램](https://koreanbots.dev/security)를 참고해주시면 감사하겠습니다.

**Comment by kyutorials** [comment]
빠른 처리 감사합니다.
