### ISSUE TITLE
[버그] 이미지가 봇 설명에 표시되지 않음

### ISSUE THREAD

**Issue by siy-uuu** [koreanbots/core#645]
## 재현방법

> 어떻게하면 발생시킬 수 있나요?

4.92MB 이상의 이미지를 추가하면 됩니다.

## 예상되는 정상적인 동작

> 정상이라면 어떻게 되야하나요?

정상적으로 이미지가 표시되어야 함.

## 발생한 문제

> 어떤 문제가 발생하나요?

이미지가 정상적으로 표시되지 않음.

## 빌드 버전

> 클라이언트의 빌드 버전을 알려주세요!

Tag: v2.6.11
Version: v2.6.10

## 사양

> OS 정보와 브라우저의 버전을 알려주세요!

Google Chrome 버전 125.0.6422.112(공식 빌드) (64비트)

## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by siy-uuu** [comment]
![2024-05-28 000839](https://github.com/koreanbots/core/assets/96490782/f3aab8dd-1bb0-4bbf-bd96-c5fcdd168243)

**Comment by eunwoo1104** [comment]
해당 문제에 대해 임시 조치가 완료되었습니다.
